import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ModalProvider from "@/components/provider/ModalProvider";
import HydrationProvider from "@/components/provider/HydrationProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Note-Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <HydrationProvider>
            <ModalProvider />
            {children}
          </HydrationProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
